# Generated by Django 4.2.3 on 2023-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.DateTimeField(max_length=100),
        ),
    ]
